# Generated by Django 2.2.14 on 2020-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200816_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haircut',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cataloge',
            new_name='catalog',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('hair_cut', 'Hair Cut'), ('product', 'Product')], default='product', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product'),
        ),
    ]
