# Generated by Django 2.2 on 2020-08-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200820_1625'),
        ('products', '0002_auto_20200819_2352'),
    ]

    operations = [
    ]
