# Generated by Django 2.2 on 2020-08-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20200820_2042'),
    ]

    operations = [
    ]
