# Generated by Django 2.2 on 2020-08-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200827_1930'),
        ('products', '0007_auto_20200826_1646'),
    ]

    operations = [
    ]
