# Generated by Django 2.2.14 on 2020-08-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20200827_2340'),
    ]

    operations = []
