# Generated by Django 2.2 on 2020-08-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200826_2037'),
        ('products', '0009_auto_20200827_2352'),
    ]

    operations = [
    ]
