# Generated by Django 2.2.14 on 2020-08-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200830_1013'),
        ('products', '0010_merge_20200830_1433'),
    ]

    operations = [
    ]
