# Generated by Django 2.2 on 2020-09-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200901_1803'),
        ('products', '0010_auto_20200830_1013'),
    ]

    operations = [
    ]
