# Generated by Django 2.2 on 2020-09-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200830_1013'),
        ('products', '0011_auto_20200901_1803'),
    ]

    operations = [
    ]
