# Generated by Django 2.2.14 on 2020-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200831_1925'),
        ('products', '0013_merge_20200910_2343'),
    ]

    operations = [
    ]
