# Generated by Django 2.2.14 on 2020-10-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201015_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
