version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./barbershop:/barbershop
    command: >
      sh -c
        "sleep 5 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=barbershop
      - DB_USER=postgres
      - DB_PASS=secretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=barbershop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword