# Generated by Django 2.2 on 2020-08-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
