# Generated by Django 2.2 on 2020-08-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200816_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
