# Generated by Django 2.2 on 2020-08-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200828_1459'),
        ('cart', '0006_auto_20200827_2352'),
    ]

    operations = [
    ]
