# Generated by Django 2.2 on 2020-08-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200829_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.FloatField(verbose_name='Сумма'),
        ),
    ]
