# Generated by Django 2.2 on 2020-09-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200828_0644'),
        ('cart', '0007_merge_20200830_1433'),
    ]

    operations = [
    ]
