# Generated by Django 2.2 on 2020-09-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_merge_20200906_1356'),
        ('cart', '0009_auto_20200904_0538'),
    ]

    operations = [
    ]
