# Generated by Django 2.2.14 on 2020-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_merge_20200910_2343'),
        ('cart', '0008_merge_20200831_1456'),
    ]

    operations = [
    ]
