# Generated by Django 2.2.14 on 2020-10-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20201006_2019'),
        ('cart', '0012_auto_20201008_1945'),
    ]

    operations = [
    ]
