# Generated by Django 2.2 on 2020-09-17 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20200813_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_id', models.IntegerField(null=True)),
                ('dt', models.DateTimeField(auto_now=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SHOPBILLID', models.IntegerField(null=True)),
                ('SHOPORDERNUMBER', models.CharField(max_length=100, null=True)),
                ('BILL_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('RESULT', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='buyer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_payment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким створено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Коли створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_email',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_surname',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('input', 'input'), ('preauth', 'preauth'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('refunded', 'refunded'), ('error', 'error')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cash', 'cash'), ('portmone', 'Portmone')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_payment_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким змінено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Коли змінено'),
        ),
    ]
