# Generated by Django 2.2 on 2020-08-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200813_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
