# Generated by Django 2.2 on 2020-08-28 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0002_auto_20200828_1527'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='workerprofile',
        #     name='worker',
        #     field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
