# Generated by Django 2.2 on 2020-08-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0003_auto_20200828_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
