# Generated by Django 2.2 on 2020-08-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker_profile', '0005_auto_20200828_1652'),
    ]

    operations = [
    ]
