# Generated by Django 2.2 on 2020-08-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0007_auto_20200828_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='other_id',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
