# Generated by Django 2.2 on 2020-08-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0010_auto_20200829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worker_profile.WorkerProfile'),
        ),
    ]
