# Generated by Django 2.2 on 2020-08-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0013_auto_20200829_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='other_id',
        ),
    ]
