# Generated by Django 2.2 on 2020-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0020_workerprofile_comm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='comm_id',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='type',
            field=models.CharField(choices=[('Facebook id', 'Facebook id'), ('Instagram id', 'Instagram id'), ('Other id', 'Other id')], default='Facebook id', max_length=50),
        ),
    ]
