# Generated by Django 2.2 on 2020-08-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0021_auto_20200829_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='social_networks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('facebook_id', 'facebook_id'), ('instagram_id', 'instagram_id'), ('other_id', 'other_id')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
