# Generated by Django 2.2 on 2020-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0024_auto_20200830_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='social_networks',
            field=models.CharField(max_length=100),
        ),
    ]
