# Generated by Django 2.2 on 2020-09-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker_profile', '0025_auto_20200901_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='social_networks',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='worker',
        ),
        migrations.CreateModel(
            name='WorkerCommunications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Коли створено')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Коли змінено')),
                ('type', models.CharField(blank=True, choices=[('facebook_id', 'facebook_id'), ('instagram_id', 'instagram_id'), ('other_id', 'other_id')], max_length=50, null=True)),
                ('social_networks_ids', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile_workercommunications_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким створено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile_workercommunications_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким змінено')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_profile.WorkerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
