# Generated by Django 2.2 on 2020-09-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker_profile', '0026_auto_20200901_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workercommunications',
            name='worker',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workercommunications',
            name='type',
            field=models.CharField(blank=True, choices=[('facebook_id', 'Facebook_id'), ('instagram_id', 'Instagram_id'), ('other_id', 'Other_id')], max_length=50, null=True),
        ),
    ]
