# Generated by Django 2.2 on 2020-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0027_auto_20200905_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercommunications',
            name='type',
            field=models.CharField(blank=True, choices=[('facebook_id', 'Facebook id'), ('instagram_id', 'Instagram id'), ('other_id', 'Other id')], max_length=50, null=True),
        ),
    ]
