# Generated by Django 2.2 on 2020-10-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0028_auto_20200912_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workercommunications',
            old_name='type',
            new_name='social_network',
        ),
    ]
