# Generated by Django 2.2.14 on 2020-08-19 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pick up', 'Pick up'), ('nova poshta', 'Nova Poshta')], default='nova poshta', max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('user_surname', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_comment', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
