# Generated by Django 2.2 on 2020-09-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='user_address',
            new_name='buyer_address',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_comment',
            new_name='buyer_comment',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_email',
            new_name='buyer_email',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_name',
            new_name='buyer_name',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_phone',
            new_name='buyer_phone',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_surname',
            new_name='buyer_surname',
        ),
    ]
