# Generated by Django 2.2 on 2020-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='user_address',
            new_name='buyer_address',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_email',
            new_name='buyer_email',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_name',
            new_name='buyer_name',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_phone',
            new_name='buyer_phone',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='user_surname',
            new_name='buyer_surname',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='buyer_comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
