# Generated by Django 2.2 on 2020-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200907_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='buyer_comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
