# Generated by Django 2.2 on 2020-09-17 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_auto_20200909_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('in transit', 'In transit'), ('arrived at destination', 'Arrived at destination'), ('delivered', 'Delivered')], default='collected', max_length=40),
        ),
    ]
