# Generated by Django 2.2 on 2020-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20200917_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(max_length=50),
        ),
    ]
