# Generated by Django 2.2 on 2020-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_auto_20200917_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('in transit', 'In transit'), ('arrived at', 'Arrived at '), ('delivered', 'Delivered')], default='collected', max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='type',
            field=models.CharField(choices=[('pick up', 'Pick up'), ('nova poshta', 'Nova Poshta')], default='nova poshta', max_length=200),
        ),
    ]
