# Generated by Django 2.2 on 2020-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_auto_20200917_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='type',
            field=models.CharField(choices=[('pick up', 'Pick up'), ('nova poshta', 'Nova Poshta')], default='nova poshta', max_length=40),
        ),
    ]
