# Generated by Django 2.2 on 2020-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_auto_20200917_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('in transit', 'In transit'), ('arrived at destination', 'Arrived at destination'), ('delivered', 'Delivered')], default='collected', max_length=40),
        ),
    ]
