# Generated by Django 2.2 on 2020-08-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Коли створено')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Коли змінено')),
                ('header', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_article_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким створено')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_article_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким змінено')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
