# Generated by Django 2.2 on 2020-08-27 09:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200825_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='blog.TaggedArticle', to='blog.ArticleTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedarticle',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_taggedarticle_items', to='blog.ArticleTag'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='articles',
            field=models.ManyToManyField(through='blog.TaggedArticle', to='blog.Article'),
        ),
    ]
