# Generated by Django 2.2 on 2020-09-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200901_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model': 'article'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
