# Generated by Django 2.2 on 2020-09-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200905_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='comment_ptr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='commentitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model': 'article'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
